var myChart = echarts.init(document.getElementById("net"));

// 定义行业类别和颜色
var categoriesData = [
  { name: "企业服务", itemStyle: { color: "#5793f3" } },
  { name: "电子商务", itemStyle: { color: "#ff7f50" } },
  { name: "汽车交通", itemStyle: { color: "#675bba" } },
  { name: "人工智能", itemStyle: { color: "#54c571" } },
  { name: "文娱传媒", itemStyle: { color: "#fdbe2d" } },
  { name: "大数据", itemStyle: { color: "#d14a61" } },
  { name: "先进制造", itemStyle: { color: "#ff9e4a" } },
  { name: "工具软件", itemStyle: { color: "#c23531" } },
  { name: "物流运输", itemStyle: { color: "#2f4554" } },
  { name: "批发零售", itemStyle: { color: "#61a0a8" } },
  { name: "硬件", itemStyle: { color: "#d48265" } },
  { name: "VR/AR", itemStyle: { color: "#91c7ae" } },
  { name: "生产制造", itemStyle: { color: "#749f83" } },
  { name: "食品饮料", itemStyle: { color: "#ca8622" } },
  { name: "环保", itemStyle: { color: "#bda29a" } },
  { name: "金融", itemStyle: { color: "#6e7074" } },
  { name: "农业", itemStyle: { color: "#546570" } },
  { name: "餐饮业", itemStyle: { color: "#c4ccd3" } },
  { name: "医疗健康", itemStyle: { color: "#f8c64d" } },
];

// 根据产品标签映射到categoriesData中的索引
var categoryMapping = {
  企业服务: 0,
  电子商务: 1,
  汽车交通: 2,
  人工智能: 3,
  文娱传媒: 4,
  大数据: 5,
  先进制造: 6,
  工具软件: 7,
  物流运输: 8,
  批发零售: 9,
  硬件: 10,
  "VR/AR": 11,
  生产制造: 12,
  食品饮料: 13,
  环保: 14,
  金融: 15,
  农业: 16,
  餐饮业: 17,
  医疗健康: 18,
};

var nodesData = [
  {
    name: "阿里巴巴",
    value: NaN,
    symbolSize: 100,
    category: categoryMapping["电子商务"],
  },
  { name: "Sealos", value: NaN, category: categoryMapping["企业服务"] },
  { name: "ABLY", value: 504, category: categoryMapping["电子商务"] },
  {
    name: "地平线机器人",
    value: 1605.36,
    category: categoryMapping["汽车交通"],
    symbolSize: 40,
  },
  { name: "星动纪元", value: 300, category: categoryMapping["人工智能"] },
  { name: "晟喜华视", value: NaN, category: categoryMapping["文娱传媒"] },
  { name: "神漫文化", value: NaN, category: categoryMapping["文娱传媒"] },
  { name: "Connectly", value: 145.94, category: categoryMapping["人工智能"] },
  { name: "Dify.AI", value: NaN, category: categoryMapping["人工智能"] },
  { name: "源络科技", value: NaN, category: categoryMapping["先进制造"] },
  {
    name: "月之暗面",
    value: 2189.13,
    category: categoryMapping["人工智能"],
    symbolSize: 45,
  },
  {
    name: "百川智能",
    value: 5000,
    category: categoryMapping["人工智能"],
    symbolSize: 45,
  },
  { name: "逐际动力", value: NaN, category: categoryMapping["人工智能"] },
  { name: "OceanBase", value: NaN, category: categoryMapping["大数据"] },
  { name: "瀚博半导体", value: NaN, category: categoryMapping["先进制造"] },
  { name: "来未来科技", value: NaN, category: categoryMapping["企业服务"] },
  { name: "iSlide", value: NaN, category: categoryMapping["工具软件"] },
  { name: "精准学", value: 200, category: categoryMapping["人工智能"] },
  {
    name: "Lazada",
    value: 15046.29,
    category: categoryMapping["电子商务"],
    symbolSize: 50,
  },
  { name: "优制娱乐", value: NaN, category: categoryMapping["文娱传媒"] },
  { name: "长佩文学", value: NaN, category: categoryMapping["文娱传媒"] },
  {
    name: "菜鸟网络",
    value: 3750,
    category: categoryMapping["物流运输"],
    symbolSize: 45,
  },
  {
    name: "MiniMax稀宇科技",
    value: 4378.26,
    category: categoryMapping["人工智能"],
  },
  {
    name: "苏宁易购",
    value: 2847,
    category: categoryMapping["批发零售"],
    symbolSize: 45,
  },
  { name: "Konvy.com", value: 80.27, category: categoryMapping["电子商务"] },
  { name: "东极六感", value: NaN, category: categoryMapping["文娱传媒"] },
  { name: "Visible", value: NaN, category: categoryMapping["企业服务"] },
  {
    name: "智谱AI",
    value: 1200,
    category: categoryMapping["人工智能"],
    symbolSize: 40,
  },
  { name: "奇点临近", value: NaN, category: categoryMapping["硬件"] },
  { name: "Wook", value: NaN, category: categoryMapping["电子商务"] },
  { name: "致敬未知", value: 72.97, category: categoryMapping["VR/AR"] },
  { name: "JBD显耀显示", value: NaN, category: categoryMapping["生产制造"] },
  { name: "左袋文化", value: NaN, category: categoryMapping["文娱传媒"] },
  { name: "COFE App", value: 109.46, category: categoryMapping["食品饮料"] },
  { name: "中测智绘", value: NaN, category: categoryMapping["先进制造"] },
  { name: "杰成新能源", value: NaN, category: categoryMapping["环保"] },
  {
    name: "WorldFirst",
    value: 3502.61,
    category: categoryMapping["金融"],
    symbolSize: 45,
  },
  { name: "博瑞迪", value: NaN, category: categoryMapping["农业"] },
  { name: "小猴科技", value: NaN, category: categoryMapping["生产制造"] },
  { name: "美小店", value: NaN, category: categoryMapping["餐饮业"] },
  { name: "恒宇医疗", value: NaN, category: categoryMapping["医疗健康"] },
];

var linksData = [
  { source: "阿里巴巴", target: "Sealos" },
  { source: "阿里巴巴", target: "ABLY" },
  { source: "阿里巴巴", target: "地平线机器人" },
  { source: "阿里巴巴", target: "星动纪元" },
  { source: "阿里巴巴", target: "晟喜华视" },
  { source: "阿里巴巴", target: "神漫文化" },
  { source: "阿里巴巴", target: "Connectly" },
  { source: "阿里巴巴", target: "Dify.AI" },
  { source: "阿里巴巴", target: "源络科技" },
  { source: "阿里巴巴", target: "月之暗面" },
  { source: "阿里巴巴", target: "百川智能" },
  { source: "阿里巴巴", target: "逐际动力" },
  { source: "阿里巴巴", target: "OceanBase" },
  { source: "阿里巴巴", target: "瀚博半导体" },
  { source: "阿里巴巴", target: "来未来科技" },
  { source: "阿里巴巴", target: "iSlide" },
  { source: "阿里巴巴", target: "精准学" },
  { source: "阿里巴巴", target: "Lazada" },
  { source: "阿里巴巴", target: "优制娱乐" },
  { source: "阿里巴巴", target: "长佩文学" },
  { source: "阿里巴巴", target: "菜鸟网络" },
  { source: "阿里巴巴", target: "MiniMax稀宇科技" },
  { source: "阿里巴巴", target: "苏宁易购" },
  { source: "阿里巴巴", target: "智谱AI" },
  { source: "阿里巴巴", target: "奇点临近" },
  { source: "阿里巴巴", target: "Wook" },
  { source: "阿里巴巴", target: "Konvy.com" },
  { source: "阿里巴巴", target: "东极六感" },
  { source: "阿里巴巴", target: "Visible" },
  { source: "阿里巴巴", target: "致敬未知" },
  { source: "阿里巴巴", target: "JBD显耀显示" },
  { source: "阿里巴巴", target: "左袋文化" },
  { source: "阿里巴巴", target: "COFE App" },
  { source: "阿里巴巴", target: "中测智绘" },
  { source: "阿里巴巴", target: "杰成新能源" },
  { source: "阿里巴巴", target: "WorldFirst" },
  { source: "阿里巴巴", target: "博瑞迪" },
  { source: "阿里巴巴", target: "小猴科技" },
  { source: "阿里巴巴", target: "美小店" },
  { source: "阿里巴巴", target: "恒宇医疗" },
];

var option = {
  title: {},
  tooltip: {},
  legend: {
    top: "10%",
    left: "left",
    orient: "vertical",
    data: categoriesData.map((item) => item.name),
  },
  series: [
    {
      name: "投资关系",
      type: "graph",
      layout: "force",
      categories: categoriesData,
      data: nodesData,
      links: linksData,
      roam: true,
      label: {
        show: true,
      },
      force: {
        repulsion: 1000,
      },
      symbolSize: 30,
    },
  ],
};

myChart.setOption(option);
